### ISSUE TITLE
Why not use $mainMod for moving windows around

### ISSUE THREAD

**Issue by Lotading** [Quezty/NixosConfiguration#3]
From binds.nix
```nix

      # Move focus with mainMod + H, J, K, L 
      "$mainMod, H, movefocus, l"
      "$mainMod, L, movefocus, r"
      "$mainMod, K, movefocus, u"
      "$mainMod, J, movefocus, d"

      # Move windows around with mainMod + shift + H, J, K, L   
      "SUPER SHIFT, H, movewindow, l"
      "SUPER SHIFT, L, movewindow, r"
      "SUPER SHIFT, K, movewindow, u"
      "SUPER SHIFT, J, movewindow, d"
      
```

**Comment by Quezty** [comment]
$mainMod is bound to SUPER further up in the config

https://github.com/Quezty/NixosConfiguration/blob/96fd8682190cb3eef955679c530509cfe1decac8/homeManagerModules/hyprland/binds.nix#L5

I will still change this to use $mainMod where SUPER is used.

**Comment by Quezty** [comment]
The lines you mentioned are now changed so they use $mainMod instead of SUPER. Thanks for pointing out the mistake!

https://github.com/Quezty/NixosConfiguration/blob/adffc11afec144d43d9f8fc95ae8c41e81d018a0/homeManagerModules/hyprland/binds.nix#L30-L34
